server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/sto
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

chainz:
  service:
    name: skcc-sto-project-local
    provider: FININ03
  server_key_service:
    url: https://dev-kong.chainz.biz/sks
  transaction_manager:
    url: https://dev-kong.chainz.biz/tx-manager
  erc20:
    url: https://dev-kong.chainz.biz/erc20
    admin: "0x3126a9dbf7c67c0d54bd634539b82f51705812db"
    recipient: "0x3126a9dbf7c67c0d54bd634539b82f51705812db"